version: "3.8"

services:
  fe:
    build:
      context: ./apps/fe
      dockerfile: docker/fe/Dockerfile
    volumes:
      - ./apps/fe:/app/apps/fe
    ports:
      - "8080:8080"
    networks:
      - sample

  api:
    build:
      context: ./apps/api
      dockerfile: docker/api/Dockerfile
    volumes:
      - ./apps/api:/app/apps/api
    ports:
      - "3000:3000"
    networks:
      - sample

  db:
    image: postgres:14
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=passw0rd
    networks:
      - sample

networks:
  sample:
    name: sample
