version: "3.8"

services:
  fe:
    build:
      context: .
      dockerfile: ./docker/fe/Dockerfile
    volumes:
      - ./apps/fe/src:/app/src
    ports:
      - "3000:3000"
    networks:
      - sample

  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    volumes:
      - ./apps/api/src:/app/src
    ports:
      - "4000:4000"
    networks:
      - sample

  db:
    image: postgres:14
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=passw0rd
    networks:
      - sample

networks:
  sample:
    name: sample

volumes:
  db-store:
